Problems utils
Sensational-Sirens/code-jam-2022 pull request #16
Opened 2022-07-23 16:42 UTC by HiPeople21

Set up Project Euler problems

2022-07-23 18:37 UTC, dignissimus reviewed
Are you able to remove the `.db` files and only include the code to recreate them?

2022-07-23 18:37 UTC, dignissimus commented on sirenity/euler/__init__.py
> +__all__ = ["problem_manager"]
You don't seem to export `problem_manager`, should this be `ProblemManager`?

2022-07-23 18:38 UTC, HiPeople21 commented on sirenity/euler/__init__.py
> +__all__ = ["problem_manager"]
You're right. I'll change this now

2022-07-23 18:38 UTC, dignissimus reviewed
Are you able to remove the .db files and only include the scripts to recreate them?
Then we can add the db files to `.gitignore` to prevent them from being kept in git.

2022-07-23 18:49 UTC, dignissimus requested changes

2022-07-23 18:49 UTC, dignissimus commented on tests/test_problems.py
> +class TestClass:
```suggestion
class TestProblemManager:
```

The name of the test class should describe what it's testing, perhaps `TestProblemManager` as a name?

2022-07-23 18:49 UTC, dignissimus commented on tests/test_problems.py
> +        assert problem.solution == "solution"
```suggestion
        self.assertEqual(problem.id, 1)
        self.assertEqual(problem.prompt, "Problem prompt")
        self.assertEqual(problem.solution, "solution")
```

The unittest library has functions for these

2022-07-23 18:49 UTC, dignissimus commented on tests/test_problems.py
> +        assert manager.check_solution("20933", 1) == False
Similar to the above reviews there is [`unittest.TestCase.assertTrue`](https://docs.python.org/3/library/unittest.html#unittest.TestCase.assertTrue) and  [`unittest.TestCase.assertFalse`](https://docs.python.org/3/library/unittest.html#unittest.TestCase.assertFalse)

2022-07-23 18:50 UTC, HiPeople21 commented on tests/test_problems.py
> +        assert problem.solution == "solution"
I though we were using pytest

2022-07-23 18:52 UTC, dignissimus commented on tests/test_problems.py
> +        assert len(cur.fetchall()) == 1
An `assertEqual` call would be appropriate here

2022-07-23 18:52 UTC, dignissimus commented on tests/test_problems.py
> +        assert problem.solution == "solution"
We are, pytest works with the unittest library

2022-07-23 18:53 UTC, dignissimus commented on tests/test_problems.py
> +        assert problem.solution == "solution"
Oh apologies, let me rethink this

2022-07-23 18:58 UTC, dignissimus commented on tests/test_problems.py
> +        assert problem.solution == "solution"
Yea, I'm happy using the `unittest` library right now and use pytest  to run tests and get coverage stats. But we might be able to drop pytest if something else can do coverage. We'll have to consider if I want it to keep pytest and work out what the advantages are of keeping it.

2022-07-23 22:24 UTC, dignissimus submitted a review, later dismissed
The db files were added to the gitignore but still exist in version control. This is a funny one, you're removing them but git isn't paying attention because it's now in the gitgnore. Try git `rm --cached` on files you don't want

2022-07-23 22:25 UTC, dignissimus commented on tests/test_problems.py
> +class TestProblemManager(unittest.TestCase):
Test functions should begin with `test_`

2022-07-23 22:29 UTC, dignissimus commented on tests/test_problems.py
> +        con.close()
When we write tests, we do it to test that the code we write works correctly no matter how the implementation changes. Tests shouldn't have implementation details inside them. You should be able to run `self.manager.add_to_db`.

A good example is your `add_and_get_problem` test.

2022-07-23 22:33 UTC, dignissimus commented on tests/test_problems.py
> +        self.check_random_problem()
If doing certain things are necessary to prepare for testing a function, you can [`setUp`](https://docs.python.org/3/library/unittest.html#unittest.TestCase.setUp) and [`tearDown`](https://docs.python.org/3/library/unittest.html#unittest.TestCase.tearDown)

2022-07-23 22:36 UTC, dignissimus commented on sirenity/euler/problems_manager.py
> +            manager.add_to_db(q[0], q[1], index)
The function definition can be inside the main body of the script

2022-07-23 22:39 UTC, dignissimus commented on tests/test_problems.py
> +            self.manager.get_at_id(2)
Not asking for a change here, but this is a really good test. Additionally, I didn't even know `assertRaises` could be used like a context manager. Good work!

2022-07-23 22:48 UTC, dignissimus commented on sirenity/euler/problems_manager.py
> +            manager.add_to_db(q[0], q[1], index)
Perhaps rename `qs` to `questions`, `f` to file and `q` to question. I didn't find it obvious what they meant

2022-07-23 22:48 UTC, dignissimus commented on tests/test_problems.py
> +        if self.manager.get_number_of_problems() == 0:
General query, should this be 0 or not?

2022-07-23 22:48 UTC, dignissimus commented on sirenity/euler/problems_manager.py
> +        return self.get_at_id(id)
`no_of_problems` can be `number_of_problems`

2022-07-23 22:48 UTC, dignissimus commented on sirenity/euler/problems_manager.py
> +        return self.get_at_id(id)
Would it be possible to run a query like this? `SELECT (id, prompt, solution) FROM problems ORDER BY RANDOM() LIMIT 1`? To get a random item

2022-07-23 22:53 UTC, dignissimus commented on sirenity/euler/problems_manager.py
> +    """Custom Exception"""
As good practice, explain what the exception is used for (even though the name makes it fairly obvious 😝).
```"""Thrown when ??? is not found"""```
Maybe name it `ProblemNotFoundError`

2022-07-23 23:00 UTC, dignissimus reviewed
Overall the code was written very well and the tests were also superb. I had a few comments to do with code-style but otherwise, the quality is fantastic and I'm very pleased with this.

2022-07-23 23:03 UTC, dignissimus commented on tests/test_problems.py
> +        self.check_random_problem()
All tests are run by default in the library. So you'd define `setUp` and `tearDown` to create the database and destroy it between test instances. If you want to setUp something only once, you can use do [`setUpClass`](https://docs.python.org/3/library/unittest.html#unittest.TestCase.setUpClass)

2022-07-24 08:03 UTC, HiPeople21 commented on tests/test_problems.py
> +        if self.manager.get_number_of_problems() == 0:
When the tests were being run on Ubuntu, it seemed like the table didn't have any rows in it, even though other tests that add the row were run before it.

2022-07-24 08:20 UTC, HiPeople21 commented on tests/test_problems.py
> +        con.close()
Sorry, I don't quite understand what you mean.

2022-07-24 12:10 UTC, dignissimus requested changes
I'm happy merging this after these have been changed

2022-07-24 12:10 UTC, dignissimus commented on sirenity/euler/problems_manager.py
> +    print(manager.get_random_problem(min_difficulty=50, max_difficulty=70))
```suggestion
def main():
    """ Run some basic functionality tests """
    manager = ProblemManager()
    manager.create_table()
    print(manager.get_random_problem())
    print(manager.get_random_problem(min_difficulty=10))
    print(manager.get_random_problem(max_difficulty=50))
    print(manager.get_random_problem(min_difficulty=50, max_difficulty=70))

if __name__ == "__main__":
    main()
```

2022-07-24 12:10 UTC, dignissimus commented on sirenity/euler/problems_manager.py
> +    import os
Even though this is only used here, it should be moved to the top of the file

2022-07-24 12:10 UTC, dignissimus commented on sirenity/euler/problems_manager.py
> +    import os
I'm referring to the import statement

2022-07-24 12:13 UTC, HiPeople21 commented on sirenity/euler/sources/prompts.txt
> +If we list all the natural numbers below 10 that are multiples of 3 or 5,
`create_sources.py` can generate the sources files

2022-07-24 13:11 UTC, dignissimus approved these changes
Well done for persevering 😂

The tests are superb, extremely extensive. 

In the future, we can try storing the data as csv and try removing some of the `type: ignore`s

2022-07-24 13:14 UTC, merged