Web ide
Sensational-Sirens/code-jam-2022 pull request #37
Opened 2022-07-26 10:49 UTC by HiPeople21

Web IDE that syncs changes between clients. (Not completely done yet)

2022-07-26 17:14 UTC, dignissimus requested changes
Nice work
* The js looks great
* The Python is good but I've requested changes to the API you've created

2022-07-26 17:14 UTC, dignissimus commented on sirenity/app.py
> +next_id = 0
1. The names of global variables must be capitalised
2. These should not be global variables
3. These should be stored inside a `Game` class. Feel free to create a small one while another Game class is being created for joining and leaving.
4. Clients should instead be a list of player objects (or potentially a dictionary, but this can be done later)

Use `flask.g`.

Setup the necessary instances of classes using
```python
@app.before_first_request
def setup_server():
    pass
```

2022-07-26 17:14 UTC, dignissimus commented on sirenity/app.py
> +    global change, next_id
See above comments

2022-07-26 17:14 UTC, dignissimus commented on sirenity/app.py
> +    await websocket.send_text(json.dumps({"action": "id", "user_id": next_id}))
It would be nice to have a (data?)class for this type of message (and all messages) instead of using dictionary literals.

`id` as an action name doesn't make it clear what this message does. I'm assuming it's for the server to receive the user's ID (is this ever checked?).

If I'm correct, try something like "identify" because the client is identifying themself. Feel free to pick a name you think clearly describes what the message is doing.

If the above is correct then, when clients receive an ID, they should also receive a token to identify themself. Use the secrets library

2022-07-26 17:14 UTC, dignissimus commented on sirenity/app.py
> +    clients.add(websocket)
Reading more of the code, it makes sense for clients to be a dictionary where the key is a user's ID and the value is the websocket

2022-07-26 17:14 UTC, dignissimus commented on sirenity/app.py
> +                await client.send_text(json.dumps(data))
`json.dumps(json.loads(...))` seems unnecessary.

Again here, I'd like a class to parse the data received via websocket.

2022-07-26 17:14 UTC, dignissimus commented on static/send-code.js
> +    var Range = require('ace/range').Range
Does this work?

2022-07-26 17:14 UTC, dignissimus commented on static/send-code.js
> +    ace.config.set("basePath", "https://cdnjs.cloudflare.com/ajax/libs/ace/1.8.1");
The JS looks very good. I might format the file with eslint for some whitespace changes.

We're not being judged on JS so this isn't something that matters at all.

2022-07-26 17:15 UTC, dignissimus commented on static/send-code.js
> +    var Range = require('ace/range').Range
Specifically the `require`

2022-07-26 17:45 UTC, HiPeople21 commented on static/send-code.js
> +    var Range = require('ace/range').Range
Yeah, I had a problem before because the Range web API would overshadow it, but it works.

2022-07-26 17:46 UTC, HiPeople21 commented on sirenity/app.py
> +                await client.send_text(json.dumps(data))
I'll remove it. There used to be a check before, but I changed the check to be on the frontend.

2022-07-26 18:39 UTC, HiPeople21 commented on sirenity/app.py
> +next_id = 0
Is there an equivalent of `flask.g` for FastAPI?

2022-07-26 23:18 UTC, dignissimus commented on sirenity/app.py
> +next_id = 0
Oh of course, I'll check because honestly I don't know

2022-07-28 18:59 UTC, HiPeople21 commented on sirenity/app.py
> +next_id = 0
Is using `contextvars` okay for this?

2022-07-30 09:40 UTC, dignissimus reviewed
The code's really good, I only want small changes to be made. I'll do them right now then merge

2022-07-30 09:40 UTC, dignissimus commented on sirenity/templates/send-code.html
> +    </style>
These should be in a css file stored in the static directory

2022-07-30 09:40 UTC, dignissimus commented on sirenity/templates/send-code.html
> +    </noscript>
These can go in a css file

2022-07-30 09:40 UTC, dignissimus commented on sirenity/message.py
> +class Message:
Nice

2022-07-30 09:40 UTC, dignissimus commented on sirenity/game_manager.py
> +            )
`os.path.dirname(__file__)` can become a global constant, we can store the database file name and the csv file name as attributes

2022-07-30 09:40 UTC, dignissimus commented on sirenity/game_manager.py
> +        if not secrets.compare_digest(self.clients[client_id].token, message.token):
Good use of secrets

2022-07-30 09:53 UTC, dignissimus commented on sirenity/app.py
> +        )
There should be a class for this

2022-07-30 09:53 UTC, dignissimus commented on sirenity/app.py
> +
I think we should set `app.game_manager` at startup

2022-07-30 12:48 UTC, HiPeople21 commented on sirenity/app.py
> +
I tried that, but mypy (I think) gave an error that FastAPI object has no attribute `game_manager`

2022-07-30 22:13 UTC, dignissimus commented on sirenity/app.py
> +
Got it

2022-07-30 22:28 UTC, dignissimus approved these changes
Not enough time to do another full review 😂

Let's pray two reviews are enough! 🙏

2022-07-30 22:36 UTC, merged